// Flat config. `npm run lint` previously invoked `expo lint` with no config present at all,
// so it either prompted or failed depending on the machine - which meant lint was effectively
// not running anywhere.
//
// The app and the Node tooling have different globals, so they get different environments:
// `src/` and `modules/` run under Metro, while `scripts/` and `test/` run under Node.

const expoConfig = require('eslint-config-expo/flat');

module.exports = [
  ...expoConfig,
  {
    ignores: [
      'node_modules/**',
      // Generated by `expo prebuild`; both are gitignored and neither is hand-edited.
      'android/**',
      'ios/**',
      '.expo/**',
      'dist/**',
      'web-build/**',
      // The navigation core is Kotlin.
      'navigation-core/**',
    ],
  },
  {
    files: ['scripts/**/*.{js,mjs}', 'test/**/*.{js,mjs}'],
    languageOptions: {
      globals: {
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
      },
    },
    rules: {
      // Diagnostics and test runners are supposed to print.
      'no-console': 'off',
    },
  },
];
